### ISSUE TITLE
Need to note that reset could be called before initialize

### ISSUE THREAD

**Issue by gmarkall** [gmarkall/nbep-7#13]
Noticed when running the test suite with the CuPy memory pool:

```
======================================================================
ERROR: test_zero_size_array (numba.cuda.tests.cudapy.test_cuda_array_interface.TestCudaArrayInterface)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nfs/gmarkall/numbadev/numba/numba/cuda/testing.py", line 19, in tearDown
    reset()
  File "/home/nfs/gmarkall/numbadev/numba/numba/cuda/cudadrv/devices.py", line 241, in reset
    _runtime.reset()
  File "/home/nfs/gmarkall/numbadev/numba/numba/cuda/cudadrv/devices.py", line 194, in reset
    self._destroy_all_contexts()
  File "/home/nfs/gmarkall/numbadev/numba/numba/cuda/cudadrv/devices.py", line 199, in _destroy_all_contexts
    gpu.reset()
  File "/home/nfs/gmarkall/numbadev/numba/numba/cuda/cudadrv/driver.py", line 555, in reset
    self.primary_context.reset()
  File "/home/nfs/gmarkall/numbadev/numba/numba/cuda/cudadrv/driver.py", line 592, in reset
    self._memory_manager.reset()
  File "/home/nfs/gmarkall/numbadev/nbep-7/nbep7/cupy_mempool.py", line 54, in reset
    self._mp.free_all_blocks()
AttributeError: 'CuPyNumbaManager' object has no attribute '_mp'

----------------------------------------------------------------------
```

`_mp` is set in `initialize`.

The specification needs to state that `reset` might get called before `initialize`, so plugins need to be robust against this.

**Comment by gmarkall** [comment]
Closing as I'm adding this to the document now.
